.env.example
.gitignore
package.json
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/main.ts
src/product/dto/bulk-product.dto.ts
src/product/dto/create-product.dto.ts
src/product/dto/product-query.dto.ts
src/product/dto/update-product.dto.ts
src/product/entities/product.entity.ts
src/product/product.controller.ts
src/product/product.module.ts
src/product/product.service.ts
tsconfig.json

- `POST /products` - Create a product
- `GET /products` - Get all products with filtering and pagination
- `GET /products/:id` - Get a specific product
- `PATCH /products/:id` - Update a product
- `DELETE /products/:id` - Delete a product
- `GET /products?search=term` - Search products
- `GET /products?category=electronics` - Filter by category
- `GET /products?brand=apple` - Filter by brand
- `GET /products?minPrice=100&maxPrice=500` - Price range filter
- `GET /products?tags=tag1,tag2` - Filter by tags
- `GET /products?sortBy=price&sortOrder=ASC` - Sorting
- `GET /products?page=1&limit=20` - Pagination
- `POST /products/bulk` - Create multiple products
- `DELETE /products/bulk` - Delete multiple products
- `PATCH /products/bulk/stock` - Update stock for multiple products
- `POST …

Product Management API - NestJS Implementation

---

src/Warehouse/controllers/inventory.controller.ts
src/Warehouse/controllers/storage-location.controller.ts
src/Warehouse/controllers/warehouse.controller.ts
src/Warehouse/dto/create-cycle-count.dto.ts
src/Warehouse/dto/create-inventory-item.dto.ts
src/Warehouse/dto/create-inventory-movement.dto.ts
src/Warehouse/dto/create-purchase-order.dto.ts
src/Warehouse/dto/create-storage-location.dto.ts
src/Warehouse/dto/create-warehouse.dto.ts
src/Warehouse/dto/update-inventory-item.dto.ts
src/Warehouse/dto/update-storage-location.dto.ts
src/Warehouse/dto/update-warehouse.dto.ts
src/Warehouse/entities/barcode.entity.ts
src/Warehouse/entities/cycle-count-item.entity.ts
src/Warehouse/entities/cycle-count.entity.ts
src/Warehouse/entities/inventory-item.entity.ts
src/Warehouse/entities/inventory-movement.entity.ts
src/Warehouse/entities/purchase-order-item.entity.ts
src/Warehouse/entities/purchase-order.entity.ts
src/Warehouse/entities/storage-location.entity.ts
src/Warehouse/entities/user.entity.ts
src/Warehouse/entities/warehouse.entity.ts
src/Warehouse/services/cycle-count.service.ts
src/Warehouse/services/inventory.service.ts
src/Warehouse/services/movement.service.ts
src/Warehouse/services/purchase-order.service.ts
src/Warehouse/services/storage-location.service.ts
src/Warehouse/services/warehouse.service.ts

✨ **Summary**  
This **PR** introduces new features like barcode management, inventory reports, cycle counting, and purchase orders, while improving maintainability, type safety, and validation. The changes include new database tables, rigorous TypeORM integration, and comprehensive testing.
closes #17 
**Key highlights:**
- 🆕 New features: Barcode management, report generation, cycle counting, purchase orders, inventory movements
- 🗄️ New entities & relations: Barcode, InventoryMovement, PurchaseOrder, CycleCount, etc.
- 🔒 Validation & error handling via DTO decorators and NestJS exceptions
- 📊 Rich reports for inventory, movements & location utilisation
- 📐 Strict TypeORM typing and repository injection everywhere
| Category                       | New / Updated Files | …

feat/Warehouse Entity and Location Management

---

src/recovery and backup/nestjs-backup-recovery-system 56.ts

backup and disaster recovery

---

src/movementService/controllers/inventory-movement.controller.ts
src/movementService/entities/batch-tracking.entity.ts
src/movementService/entities/inventory-movement.dto.ts
src/movementService/entities/inventory-movement.entity.ts
src/movementService/entities/stock-alert.entity.ts
src/movementService/entities/stock-level.entity.ts
src/movementService/entities/stock-reservation.entity.ts
src/movementService/inventory-movement.module.ts
src/movementService/inventory-movement.service.ts

This PR introduces a comprehensive `MovementService` domain to handle all inventory movement workflows within the LyricsFlip Inventory system. The service provides capabilities ranging from basic stock operations to advanced forecasting and batch management.
closes #25 
- **Stock Operations**: Stock-In, Stock-Out, Transfer, and Adjustment operations with atomic DB transactions
- **Approval Workflow**: Movement lifecycle (PENDING → APPROVED/REJECTED → IN_PROGRESS → COMPLETED) with auto-approval for urgent moves
- **Bulk Processing**: `bulkMovements` and `atomicBulkMovements` endpoints for efficient batch processing
- **Reservations**: Hold/release inventory for orders without physical movement
- **Dynamic Stock Levels**: Min/Max/Re-order point management with automatic alerting
- **Smart …

feat/Inventory Movement Service

---

src/Performance Monitoring/alerting.service.ts
src/Performance Monitoring/api-response.interceptor.ts
src/Performance Monitoring/database-monitoring.service.ts
src/Performance Monitoring/error-monitoring.service.ts
src/Performance Monitoring/metrics.controller.ts
src/Performance Monitoring/performance-monitoring.module.ts
src/Performance Monitoring/performance.service.ts

performance monitoring

---

package.json
src/product/barcode.service.ts
src/product/entities/location.entity.ts
src/product/entities/product.entity.ts
src/product/product.service.ts
utils/barcode.util.ts

Feature: Barcode Generation for Products
Summary
This PR adds support for generating and validating barcodes for products using the EAN-13 format. It introduces a BarcodeService utility and integrates it into the ProductService to automatically generate a barcode when creating a product.
What's Included
BarcodeService for generating and validating barcodes
BarcodeFormat enum and barcode utility helpers (generateBarcode, validateEAN13)
nanoid used for barcode uniqueness (installed and typed)
Product entity updated to include barcode field
ProductService:
Automatically generates a barcode during product creation
Supports finding products by barcode (findProductByBarcode)
Unit-safe and scalable integration for additional barcode formats in the future
Tech Stack
NestJS
PostgreSQL + TypeORM …

feat:Barcode Generation Service #33

---

package.json
src/main.ts

feat: configure CORS for frontend integration
- Add CORS middleware with environment-based origin configuration
- Implement security headers using helmet
- Configure preflight request handling with caching
- Add environment variable for frontend URL
- Set up allowed methods and headers for API access

feat: configure CORS for frontend integratio

---

.env.example
package.json
src/app.module.ts
src/main.ts
src/notification/dto/create-notification.dto.ts
src/notification/dto/send-notification.dto.ts
src/notification/dto/update-notification.dto.ts
src/notification/endpoint.http
src/notification/entities/inapp-notification.entity.ts
src/notification/entities/notification.entity.ts
src/notification/interfaces/notification-channel.interface.ts
src/notification/notification.controller.ts
src/notification/notification.module.ts
src/notification/services/ in-app-notification.service.ts
src/notification/services/dispatcher.service.ts
src/notification/services/email-notification.service.ts
src/notification/services/notification.service.ts
src/notification/services/sms-notification.service.ts
src/preference/dto/create-preference.dto.ts
src/preference/dto/update-preference.dto.ts
src/preference/entities/preference.entity.ts
src/preference/preference.controller.ts
src/preference/preference.module.ts
src/preference/services/preference.service.ts

This Pull Request introduces a robust and standardized approach to input validation and response transformation across the API. By leveraging `class-validator` and `class-transformer`, we ensure that incoming request payloads adhere to defined schemas and that outgoing responses are consistently formatted and free from sensitive data.
1.  **Installation of Dependencies:**
-   Added `class-validator` and `class-transformer` to `package.json`.
2.  **Global Validation Pipe:**
-   Configured `app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }))` in `src/main.ts`.
-   `whitelist: true`: Ensures that only properties defined in the DTO are allowed in the request body, stripping out any unknown properties. This prevents unexpected data from being processed.
-   `transform: …

feat: add global validation pipe

---

src/Hospital Configuration Management/hospital-config/dto/hospital-config.controller.ts
src/Hospital Configuration Management/hospital-config/dto/hospital-config.dto.ts
src/Hospital Configuration Management/hospital-config/dto/hospital-config.module.ts
src/Hospital Configuration Management/hospital-config/entities/hospital-config.entity.ts
src/Hospital Configuration Management/hospital-config/hospital-config.service.ts

advance search

---

src/Purchase Order API Endpoints/approve-purchase-order.dto.ts
src/Purchase Order API Endpoints/create-purchase-order.dto.ts
src/Purchase Order API Endpoints/purchase-order.controller.ts
src/Purchase Order API Endpoints/purchase-order.entity.ts
src/Purchase Order API Endpoints/purchase-order.module.ts
src/Purchase Order API Endpoints/purchase-order.service.ts
src/Purchase Order API Endpoints/supplier.entity.ts
src/Purchase Order API Endpoints/update-purchase-order.dto.ts

purchase order

---

src/purchase-order/dto/approve-purchase-order.dto.ts
src/purchase-order/dto/create-purchase-order.dto.ts
src/purchase-order/dto/receive-goods.dto.ts
src/purchase-order/dto/update-purchase-order.dto.ts
src/purchase-order/entities/purchase-order-item.entity.ts
src/purchase-order/entities/purchase-order.entity.ts
src/purchase-order/entities/supplier.entity.ts
src/purchase-order/purchase-order.controller.ts
src/purchase-order/purchase-order.module.ts
src/purchase-order/purchase-order.service.ts

This PR implements a comprehensive Purchase Order Lifecycle Management System that fulfills all business requirements for order creation, validation, approval workflow, and goods receiving process with seamless inventory integration.
✅ Order creation and validation
✅ Approval workflow
✅ Receiving goods process
✅ Order status updates
src/purchase-order/
├── entities/
│   ├── purchase-order.entity.ts
│   ├── supplier.entity.ts 
│   └── purchase-order-item.entity.ts
├── dto/
│   ├── create-purchase-order.dto.ts
│   ├── update-purchase-order.dto.ts
│   ├── approve-purchase-order.dto.ts
│   └── receive-goods.dto.ts
├── purchase-order.service.ts
├── purchase-order.controller.ts
└── purchase-order.module.ts
This PR Closes #27

feat: implement purchase order service

---

.env.example
src/app.module.ts
src/config/config.module.ts
src/config/config.service.ts
src/config/environment.config.ts
src/main.ts

worked on Environment Configuration Management

---

src/permissionSystem/controllers/permission.controller.ts
src/permissionSystem/controllers/role.controller.ts
src/permissionSystem/controllers/user-role.controller.ts
src/permissionSystem/decorators/permissions.decorator.ts
src/permissionSystem/dto/create-role.dto.ts
src/permissionSystem/dto/update-permission.dto.ts
src/permissionSystem/dto/update-role.dto.ts
src/permissionSystem/entities/permission.entity.ts
src/permissionSystem/entities/role.entity.ts
src/permissionSystem/entities/user.entity.ts
src/permissionSystem/guards/permissions.guard.ts
src/permissionSystem/permission-system.module.ts
src/permissionSystem/services/permission.service.ts
src/permissionSystem/services/role.service.ts
src/permissionSystem/services/user-role.service.ts

Define Role and Permission Entities
Create data models for roles and permissions.
Establish User-Role Relationships
Link users to specific roles in the system (e.g., Admin, Editor, Viewer).
Implement Permission-Based Guards
Set up middleware or route guards to restrict access based on user permissions.
Develop Role Management Endpoints
Create APIs to assign roles, manage permissions, and update role data.
Close #23

created the user permission system

---

src/movementService/email.service.ts
src/movementService/inventory-movement.service.ts
src/movementService/stock-alert.service.ts

- Checked and confirmed the correctness of EmailService and StockAlertService implementations
- Ensured proper error handling, dependency injection, and environment variable usage
- Verified email notification logic for inventory alerts
- Confirmed code structure and best practices for maintainability

Review and verify inventory alert and email service logic

---

package.json
src/categories/categories.controller.ts
src/categories/categories.module.ts
src/categories/categories.repository.ts
src/categories/categories.service.ts
src/categories/dto/create-category.dto.ts
src/categories/dto/update-category.dto.ts
src/categories/entities/category.entity.ts
src/products/entities/product.entity.ts

feat: Implement Category Entity and Relationships

---

src/Multi-tenant/auth/guards/tenant-auth.guard.ts
src/Multi-tenant/tenant/decorators/tenant-repository.decorator.ts
src/Multi-tenant/tenant/entities/tenant.entity.ts
src/Multi-tenant/tenant/middleware/tenant.middleware.ts
src/Multi-tenant/tenant/resolvers/header-tenant.resolver.ts
src/Multi-tenant/tenant/tenant-config.service.ts
src/Multi-tenant/tenant/tenant-database.service.ts
src/Multi-tenant/tenant/tenant-migration.service.ts
src/Multi-tenant/tenant/tenant.module.ts
src/Multi-tenant/user/user.service.ts

Priority: Low
Description:
This PR adds multi-tenant support to enable the system to securely serve multiple companies and branches within a single deployment. The implementation focuses on strict tenant isolation and flexibility in configuration.
Key Features & Acceptance Criteria:
✅ Tenant Isolation at Database Level
Each tenant's data is isolated to prevent cross-tenant access and ensure data security and integrity.
✅ Tenant-Aware Authentication
Authentication flow updated to be tenant-aware, ensuring users only access data within their respective tenant context.
✅ Tenant-Specific Configurations
Support for per-tenant configuration of features, UI settings, and business logic.
✅ Data Migration Between Tenants
Introduces tools and safeguards to allow controlled data migration between …

feat"added multi-tenant"

---

src/inventory/entities/inventory-item.entity.ts
src/inventory/entities/reservation.entity.ts
src/inventory/entities/valuation-record.entity.ts
src/inventory/inventory.module.ts
src/inventory/inventory.service.ts
src/inventory/stock-level.service.ts
src/inventory/valuation.controller.ts
src/sales-order/dto/create-sales-order.dto.ts
src/sales-order/dto/update-sales-order.dto.ts
src/sales-order/entities/order-item.entity.ts
src/sales-order/entities/sales-order.entity.ts
src/sales-order/sales-order.controller.ts
src/sales-order/sales-order.module.ts
src/sales-order/sales-order.service.ts

closes #26 
- Introduce `Reservation` entity for managing active, released, and fulfilled holds
- Implement `StockLevelService` with:
- `getRealTimeStock(sku, locationId)` → on-hand, reserved, available
- `reserveStock(...)`, `releaseReservation(...)`, `fulfillReservation(...)`
- `reconcileStock(...)` to compare expected vs actual and emit adjustments
- Wire new service and entity into `InventoryModule`
- Enable accurate, real-time visibility into inventory availability
- Support reservation workflows for order holds
- Provide reconciliation tools to correct discrepancies
- Unit tests for each service method (edge cases: over-reservation, double release, reconciliation no-op)
- Integration tests covering end-to-end reservation → fulfillment → stock update
- e2e scenario: create …

Real time stock level

---

Advanced Security Features/src/security/controllers/security.controller.ts
Advanced Security Features/src/security/decorators/encrypted-field.decorator.ts
Advanced Security Features/src/security/guards/signature.guard.ts
Advanced Security Features/src/security/interceptors/encryption.interceptor.ts
Advanced Security Features/src/security/middleware/audit.middleware.ts
Advanced Security Features/src/security/middleware/security-monitoring.middleware.ts
Advanced Security Features/src/security/middleware/signing.middleware.ts
Advanced Security Features/src/security/security.module.ts
Advanced Security Features/src/security/services/audit.service.ts
Advanced Security Features/src/security/services/encryption.service.ts
Advanced Security Features/src/security/services/security-monitoring.service.ts
Advanced Security Features/src/security/services/signing.service.ts
Advanced Security Features/src/security/types/security.types.ts

Advance Security

---

package.json
src/app.module.ts
src/barcode/barcode.controller.ts
src/barcode/barcode.module.ts
src/barcode/barcode.service.ts

- Implemented barcode module, controller, and service
- Supports barcode generation for multiple formats (code128, ean13, qrcode)
- Added barcode validation and supported formats endpoint
- Integrated barcode module with the main app

feat: add Barcode Generation Service (closes #33)

---

package.json
src/app.module.ts
src/product management/dto/bulk-product.dto.ts
src/product management/dto/create-product.dto.ts
src/product management/dto/product-query.dto.ts
src/product management/dto/update-product.dto.ts
src/product management/entities/product-image.entity.ts
src/product management/entities/product.entity.ts
src/product management/product-management.controller.ts
src/product management/product-management.module.ts
src/product management/product-management.service.ts

feat: added product management module

---

src/load-tests/patient-access.test.js

This PR implements a complete performance optimization and scalability readiness suite as part of the system hardening initiative.
---
- 🔬 **Load Testing Suite with K6**  
- Simulates up to 100 concurrent users on key patient endpoints  
- Scripted and reusable test scenarios under `load-tests/`
- 🧵 **Database Connection Pooling Optimization**  
- Increased max connections and improved idle/timeout handling for PostgreSQL  
- Ready for connection poolers like `pgBouncer`
- ⚡ **Caching Strategy**  
- Introduced `@nestjs/cache-manager` for patient data caching  
- Reduces DB pressure on repeated GET requests
- 📦 **Horizontal Scaling Preparation**  
- App made stateless and container-friendly  
- Supports environment-based port config for multi-instance deployment
---
- `load-tests/` – K6 …

feat: implement load testing, DB pooling, caching, and horizontal scaling readiness

---

src/load-tests/patient-access.test.js
src/report/report.controller.ts
src/report/report.service.ts
src/report/templates/inventory-report.template.ts
src/report/utils/excel-export.util.ts
src/report/utils/pdf-export.util.ts

This PR enhances the inventory report system to support exporting reports in **PDF and Excel formats**, using a flexible and scalable strategy pattern.
---
- 🧠 **Strategy-based report generation**
- Dynamically resolves strategy by report type
- Clean extensibility for new report types
- 📤 **Export Support**
- Supports PDF export using HTML template + `html-pdf`
- Supports Excel export using `exceljs`
- File naming includes timestamp
- Temporary file paths (`/tmp/...`) used for now
- 📄 **Template System**
- Inventory report HTML used for PDF layout
- Table includes name, SKU, quantity, location, updated date
- 🕓 **Scheduled Reports**
- Daily cron continues to generate & export reports
- Shared export utility reused
---
- ✅ GET `/report/:id/export?format=pdf` → returns PDF path
- ✅ GET …

 Add PDF/Excel Export to Inventory Report Engine with Strategy Pattern Support

---

src/main.ts

feat: implement CORS configuration for frontend integration
- Add CORS middleware with environment-based origin configuration
- Configure allowed methods, headers, and credentials support
- Enable preflight request handling with 1-hour cache
- Implement security headers using Helmet middleware
- Support dynamic frontend URL via FRONTEND_URL environment variable
- Add fallback to localhost:5173 for development environment
Resolves: Configure Cross-Origin Resource Sharing for frontend integration

feat: implement CORS configuration for frontend integration

---

src/User Resource Module/app.module.ts
src/User Resource Module/dto/create-user.dto.ts
src/User Resource Module/dto/update-user.dto.ts
src/User Resource Module/dto/user-query.dto.ts
src/User Resource Module/dto/user-response.dto.ts
src/User Resource Module/exceptions/user-already-exists.exception.ts
src/User Resource Module/exceptions/user-not-found.exception.ts
src/User Resource Module/user.controller.ts
src/User Resource Module/user.entity.ts
src/User Resource Module/user.module.ts
src/User Resource Module/user.service.ts
src/User Resource Module/validation/validation.pipe.ts

User Resource Module

---

src/purchase-orders/dto/add-purchase-order-item.dto.ts
src/purchase-orders/dto/create-purchase-order.dto.ts
src/purchase-orders/dto/update-purchase-order.dto.ts
src/purchase-orders/entities/purchase-order-history.entity.ts
src/purchase-orders/entities/purchase-order-item.entity.ts
src/purchase-orders/entities/purchase-order.entity.ts
src/purchase-orders/purchase-orders.controller.ts
src/purchase-orders/purchase-orders.module.ts
src/purchase-orders/purchase-orders.service.ts

Purchase-Order-Resource-Module

---

src/app.module.ts
src/auth/guards/company.guard.ts
src/categories/categories.controller.ts
src/categories/categories.module.ts
src/categories/categories.service.ts
src/categories/category.entity.ts
src/categories/dto/create-category.dto.ts
src/categories/dto/update-category.dto.ts
src/inventory-items/dto/inventory-item-query.dto.ts
src/inventory-items/inventory-items.module.ts
src/inventory-items/inventory-items.service.ts

Implemented a full Categories feature with a self-referencing 
Category entity (parentId, parent, children) and unique [companyId, name], plus a guarded controller and service providing CRUD, children, and tree endpoints with circular-hierarchy prevention; added usage stats per node (itemsDirect, itemsWithDescendants) by counting InventoryItem.category matches; integrated module wiring (CategoriesModule, autoLoadEntities in app.module.ts) and created CompanyGuard; extended inventory item queries to support hierarchical filtering via categoryId (expands to descendant category names) while retaining exact-name category filtering; updated 
InventoryItemsModuleand service to inject Categoryand apply the new filter.
Close #130

implemeted the categrory resource module

---

src/app.module.ts
src/auth/auth.service.ts
src/auth/decorators/roles.decorator.ts
src/auth/guards/roles.guard.ts
src/auth/strategies/jwt.strategy.ts
src/common/types/jwt-payload.type.ts
src/rbac/controllers/permissions.controller.ts
src/rbac/controllers/roles.controller.ts
src/rbac/decorators/permissions.decorator.ts
src/rbac/decorators/roles.decorator.ts
src/rbac/entities/permission.entity.ts
src/rbac/entities/role.entity.ts
src/rbac/guards/permissions.guard.ts
src/rbac/guards/roles.guard.ts
src/rbac/permissions.controller.ts
src/rbac/rbac.module.ts
src/rbac/rbac.seeder.ts
src/rbac/rbac.service.spec.ts
src/rbac/roles.controller.ts
src/rbac/services/permissions.service.ts
src/rbac/services/rbac.service.ts
src/rbac/services/roles.service.ts
src/rbac/services/user-roles.service.ts
src/rbac/user-roles.controller.ts
src/users/user.entity.ts
src/users/users.service.ts

Closes #128 
- Add Role and Permission entities with proper relationships
- Implement RolesService and PermissionsService with full CRUD operations
- Create UserRolesService for user-role associations
- Add RbacService for permission checking
- Implement PermissionsGuard and RolesGuard for route protection
- Create @Permissions() and @RequireRole() decorators
- Add role hierarchy inheritance support
- Secure all RBAC endpoints with appropriate permissions
- Include comprehensive RBAC seeder with default roles
- Add unit tests 
- Fix deprecated TypeORM methods and import paths

feat: implement comprehensive RBAC system withroles and permissions
